name: nightly

on:
  schedule:
    # 00:00 UTC every day
    - cron: '0 0 * * *' 
  workflow_dispatch:
    # Manual run

jobs:
  build:
    - name: Setup rclone
      run: |
        echo ${{ secrets.RCLONE_CONFIG }} | base64
